name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * wed"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  determine-environments:
    runs-on: ubuntu-latest

    outputs:
      environments: ${{ steps.environments.outputs.environments }}

    steps:
      # smoelius: The Windows job runs more slowly than the Ubuntu and macOS jobs. So run it only
      # when the triggering event is `schedule` or `workflow_dispatch`. See also the comment
      # preceding `RAYON_NUM_THREADS` below.
      - name: Determine environments
        id: environments
        run: |
          if [[ '${{ github.event_name }}' == 'schedule' || '${{ github.event_name }}' == 'workflow_dispatch' ]]; then
            echo 'environments=["ubuntu-latest", "macos-latest", "windows-latest"]' >> "$GITHUB_OUTPUT"
          else
            echo 'environments=["ubuntu-latest", "macos-latest"]' >> "$GITHUB_OUTPUT"
          fi

  test:
    needs: [determine-environments]

    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJSON(needs.determine-environments.outputs.environments) }}

    runs-on: ${{ matrix.environment }}

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v7

      - uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.dylint_drivers/
            ~/.rustup/toolchains/
            target/dylint/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Update and install toolchains
        run: |
          rustup toolchain update beta --profile minimal
          rustup install stable
          rustup default stable
          rustc -vV

      - name: Install tools
        run: |
          rustup update
          rustup install nightly
          rustup component add clippy --toolchain nightly
          cargo install cargo-dylint dylint-link         || true
          cargo install cargo-msrv --no-default-features || true
          cargo install cargo-supply-chain               || true
          cargo install unset                            || true

      - name: Build
        run: cargo build --workspace --all-targets

      - name: Test all but example
        env:
          # Limit `trycmd` concurrency on Windows. Its cases invoke Cargo in parallel, which can
          # otherwise cause enough contention to trigger libtest's 60-second status message.
          RAYON_NUM_THREADS: ${{ runner.os == 'Windows' && '1' || '0' }}
        run: cargo test --workspace --exclude nested_workspace_example --config "target.'cfg(all())'.runner = 'unset'" -- --nocapture

      - name: Test example
        run: cargo test -p nested_workspace_example -- --nocapture

  all-checks:
    needs: [determine-environments, test]

    if: ${{ always() }}

    runs-on: ubuntu-latest

    steps:
      - name: Check results
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
